# site
url: #
author: lorenzoantei
title: "weirdGallery" # the name of your site, e.g. ACME Corp.

# markdown
markdown: kramdown
highlighter: rouge

# plugins:
#  - jekyll-seo-tag

# google analytics
#google_analytics_id: "Google Analytics ID"

# other configs
exclude: ["CNAME", "README.md"]
